/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forme;

import domen.Korisnik;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Rastko
 */
public class GlavnaForma extends javax.swing.JFrame {
    Korisnik ulogovaniKorisnik;

    /** Creates new form GlavnaForma */
    public GlavnaForma() throws IOException {
        initComponents();
        
        
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUlogovaniKorisnik = new javax.swing.JLabel();
        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPlivaci = new javax.swing.JMenu();
        jmiNoviPlivac = new javax.swing.JMenuItem();
        jmTrke = new javax.swing.JMenu();
        jmiNovaTrka = new javax.swing.JMenuItem();
        jmiPretrazi = new javax.swing.JMenuItem();
        jmiIzmeni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Svetsko prvenstvo - Glavna forma");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Korisnik"));
        jPanel1.setToolTipText("");

        lblUlogovaniKorisnik.setText("Ulogovani korisnik:");

        lblUlogovani.setText("Ime i prezime ulogovanog korisnika");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovaniKorisnik)
                .addGap(18, 18, 18)
                .addComponent(lblUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovaniKorisnik)
                    .addComponent(lblUlogovani))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jmPlivaci.setText("Plivači");

        jmiNoviPlivac.setText("Novi");
        jmiNoviPlivac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviPlivacActionPerformed(evt);
            }
        });
        jmPlivaci.add(jmiNoviPlivac);

        jMenuBar1.add(jmPlivaci);

        jmTrke.setText("Trke");

        jmiNovaTrka.setText("Nova");
        jmiNovaTrka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovaTrkaActionPerformed(evt);
            }
        });
        jmTrke.add(jmiNovaTrka);

        jmiPretrazi.setText("Pretrazi");
        jmiPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziActionPerformed(evt);
            }
        });
        jmTrke.add(jmiPretrazi);

        jmiIzmeni.setText("Izmeni");
        jmiIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmeniActionPerformed(evt);
            }
        });
        jmTrke.add(jmiIzmeni);

        jMenuBar1.add(jmTrke);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziActionPerformed
        TrkePretragaForma tpf =  new TrkePretragaForma(this, true);
        tpf.setVisible(true);
    }//GEN-LAST:event_jmiPretraziActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jmiNoviPlivacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviPlivacActionPerformed
        FormaDodajPlivača fdp = new FormaDodajPlivača();
        fdp.setVisible(true);
    }//GEN-LAST:event_jmiNoviPlivacActionPerformed

    private void jmiIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmeniActionPerformed
        TrkePretragaForma tpf =  new TrkePretragaForma(this, true);
        tpf.setVisible(true);
    }//GEN-LAST:event_jmiIzmeniActionPerformed

    private void jmiNovaTrkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovaTrkaActionPerformed
        TrkeForma tf = new TrkeForma();
        tf.setVisible(true);
    }//GEN-LAST:event_jmiNovaTrkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GlavnaForma().setVisible(true);
                    
                    
                } catch (IOException ex) {
                    Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmPlivaci;
    private javax.swing.JMenu jmTrke;
    private javax.swing.JMenuItem jmiIzmeni;
    private javax.swing.JMenuItem jmiNovaTrka;
    private javax.swing.JMenuItem jmiNoviPlivac;
    private javax.swing.JMenuItem jmiPretrazi;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JLabel lblUlogovaniKorisnik;
    // End of variables declaration//GEN-END:variables

    public void setUlogovani(Korisnik ulogovaniKorisnik) {
        this.ulogovaniKorisnik = ulogovaniKorisnik;
        lblUlogovani.setText(ulogovaniKorisnik.getImePrezime()+"");
                
    }

    

    

    

}
