/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Trka;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.KontrolerKI;
import modeli.ModelTabeleTrke;

/**
 *
 * @author Rastko
 */
public class TrkePretragaForma extends javax.swing.JDialog {
    private KontrolerKI kontrolerKI;

    /**
     * Creates new form TrkePretragaForm
     */
    public TrkePretragaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kontrolerKI = new KontrolerKI();
        kontrolerKI.srediTabeluTrke(this, tabelaTrke);
        kontrolerKI.pripremiTabeluTrkeZaSort(this, tabelaTrke, txtPretraziTrke);
    }

    TrkePretragaForma() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTrke = new javax.swing.JTable();
        lblPretraziTrke1 = new javax.swing.JLabel();
        txtPretraziTrke = new javax.swing.JTextField();
        btnUnesiRezultate = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnDodajNovu = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Svetsko prvenstvo u plivanju - pretraga trka");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trke"));

        tabelaTrke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaTrke);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblPretraziTrke1.setText("Pretraži trke: ");

        btnUnesiRezultate.setText("Unesi rezultate");
        btnUnesiRezultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiRezultateActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši trku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnDodajNovu.setText("Dodaj novu trku");
        btnDodajNovu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovuActionPerformed(evt);
            }
        });

        btnPrikazi.setText("Prikaži trku");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodajNovu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUnesiRezultate)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(lblPretraziTrke1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPretraziTrke, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesiRezultate)
                    .addComponent(btnObrisi)
                    .addComponent(btnDodajNovu)
                    .addComponent(btnPrikazi))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPretraziTrke1)
                        .addComponent(txtPretraziTrke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNovuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovuActionPerformed
        TrkeForma tf = new TrkeForma();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDodajNovuActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int red = tabelaTrke.getSelectedRow();
        if(red != -1) {
            ModelTabeleTrke mtt = (ModelTabeleTrke) tabelaTrke.getModel();
            ArrayList<Trka> listaTrka = mtt.getListaTrka();
            Trka trka = listaTrka.get(red);
            TrkeForma tf = new TrkeForma(trka);
            
            tf.prikaziTrku(red, tabelaTrke);
            tf.setVisible(true);
            this.setVisible(false);
        }else {
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali trku");
            return;
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
       int red = tabelaTrke.getSelectedRow();
       if(red != -1) {
           kontrolerKI.obrisiTrku(this, red, tabelaTrke);
       }else{
           JOptionPane.showMessageDialog(rootPane, "Nije odabrana trka!");
           return;
       }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnUnesiRezultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiRezultateActionPerformed
        int red = tabelaTrke.getSelectedRow();
        if(red != -1) {
            
            TrkeForma tf = new TrkeForma();
            try {
                tf.unesiRezultate(red, tabelaTrke);
                tf.setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vec su uneti rezultati za ovu trku");
                tf.dispose();
            }
           
        }else {
            JOptionPane.showMessageDialog(rootPane, "Trka nije odabrana!");
        }
    }//GEN-LAST:event_btnUnesiRezultateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrkePretragaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrkePretragaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrkePretragaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrkePretragaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrkePretragaForma dialog = new TrkePretragaForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNovu;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnUnesiRezultate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPretraziTrke1;
    private javax.swing.JTable tabelaTrke;
    private javax.swing.JTextField txtPretraziTrke;
    // End of variables declaration//GEN-END:variables
}
