/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Plivac;
import domen.Trka;
import domen.Ucesce;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import kontroler.KontrolerKI;
import modeli.ModelTabeleUcesce;

/**
 *
 * @author Rastko
 */
public class TrkeForma extends javax.swing.JFrame {
    private KontrolerKI kontrolerKI;
    Trka trka;

    /**
     * Creates new form TrkeForma
     */
    public TrkeForma() {
        initComponents();
        kontrolerKI = new KontrolerKI();
        srediTabeluUcesca();
        KontrolerKI.ucitajKomboVrste(this, cmbVrstaTrke);
    }

    public TrkeForma(Trka trka) {
        initComponents();
        kontrolerKI = new KontrolerKI();
        srediTabeluUcesca();
        KontrolerKI.ucitajKomboVrste(this, cmbVrstaTrke);
        this.trka = trka;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDuzina = new javax.swing.JLabel();
        txtDuzina = new javax.swing.JTextField();
        lblDrzava = new javax.swing.JLabel();
        txtDrzava = new javax.swing.JTextField();
        lblPlivaliste = new javax.swing.JLabel();
        txtPlivaliste = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        lblVreme = new javax.swing.JLabel();
        txtVreme = new javax.swing.JTextField();
        lblFaza = new javax.swing.JLabel();
        txtFaza = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblEvropski = new javax.swing.JLabel();
        lblSvetski = new javax.swing.JLabel();
        lblOlimpijski = new javax.swing.JLabel();
        txtEvropski = new javax.swing.JTextField();
        txtSvetski = new javax.swing.JTextField();
        txtOlimpijski = new javax.swing.JTextField();
        lblBrojUcesnika = new javax.swing.JLabel();
        txtBrojUcesnika = new javax.swing.JTextField();
        lblVrsta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUcesce = new javax.swing.JTable();
        btnIzmeniTrku = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnSacuvajTrku = new javax.swing.JButton();
        btnObrisiUcesce = new javax.swing.JButton();
        btnDodajUcesca = new javax.swing.JButton();
        cmbVrstaTrke = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Svetsko prvenstvo - Trke");

        lblDuzina.setText("Dužina:");

        lblDrzava.setText("Država:");

        txtDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrzavaActionPerformed(evt);
            }
        });

        lblPlivaliste.setText("Naziv plivališta:");

        txtPlivaliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlivalisteActionPerformed(evt);
            }
        });

        lblDatum.setText("Datum:");

        txtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumActionPerformed(evt);
            }
        });

        lblVreme.setText("Vreme:");

        lblFaza.setText("Faza:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rekordi"));
        jPanel1.setToolTipText("Rekordi");

        lblEvropski.setText("Evropski: ");

        lblSvetski.setText("Svetski:");

        lblOlimpijski.setText("Olimpijski:");

        txtOlimpijski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOlimpijskiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvropski)
                    .addComponent(lblSvetski)
                    .addComponent(lblOlimpijski))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEvropski)
                    .addComponent(txtSvetski)
                    .addComponent(txtOlimpijski, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvropski)
                    .addComponent(txtEvropski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSvetski)
                    .addComponent(txtSvetski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOlimpijski)
                    .addComponent(txtOlimpijski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblBrojUcesnika.setText("Broj učesnika:");

        lblVrsta.setText("Vrsta trke:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Učešća"));

        tabelaUcesce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUcesce);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzmeniTrku.setText("Izmeni trku");
        btnIzmeniTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniTrkuActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnSacuvajTrku.setText("Sačuvaj trku");
        btnSacuvajTrku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajTrkuActionPerformed(evt);
            }
        });

        btnObrisiUcesce.setText("Obrisi ucesce");
        btnObrisiUcesce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUcesceActionPerformed(evt);
            }
        });

        btnDodajUcesca.setText("Dodaj ucesca");
        btnDodajUcesca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUcescaActionPerformed(evt);
            }
        });

        cmbVrstaTrke.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDodajUcesca)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiUcesce))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSacuvajTrku)
                            .addGap(18, 18, 18)
                            .addComponent(btnIzmeniTrku)
                            .addGap(18, 18, 18)
                            .addComponent(btnOtkazi))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVrsta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbVrstaTrke, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDrzava)
                                            .addComponent(lblDuzina))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDrzava, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(txtDuzina)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPlivaliste)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPlivaliste, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVreme)
                                            .addComponent(lblFaza)
                                            .addComponent(lblBrojUcesnika))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFaza, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(txtVreme)
                                            .addComponent(txtBrojUcesnika)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lblDatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuzina)
                            .addComponent(txtDuzina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatum)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDrzava)
                            .addComponent(txtDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVreme)
                            .addComponent(txtVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlivaliste)
                            .addComponent(txtPlivaliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaza)
                            .addComponent(txtFaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrojUcesnika)
                            .addComponent(txtBrojUcesnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrsta)
                    .addComponent(cmbVrstaTrke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiUcesce)
                    .addComponent(btnDodajUcesca))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnIzmeniTrku)
                    .addComponent(btnSacuvajTrku))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniTrkuActionPerformed
        kontrolerKI.izmeniTrku(this, trka, txtDuzina, txtDrzava, txtPlivaliste, txtDatum, txtVreme, txtFaza, txtBrojUcesnika, txtEvropski, txtSvetski, txtOlimpijski, cmbVrstaTrke);
    }//GEN-LAST:event_btnIzmeniTrkuActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
       dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnSacuvajTrkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajTrkuActionPerformed
        kontrolerKI.sacuvaTrku(this, tabelaUcesce, txtDuzina, txtDrzava, txtPlivaliste, txtDatum, txtVreme, txtFaza, txtBrojUcesnika, txtEvropski, txtSvetski, txtOlimpijski, cmbVrstaTrke, btnSacuvajTrku);
    }//GEN-LAST:event_btnSacuvajTrkuActionPerformed

    private void txtDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrzavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrzavaActionPerformed

    private void txtPlivalisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlivalisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlivalisteActionPerformed

    private void txtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumActionPerformed

    private void txtOlimpijskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOlimpijskiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOlimpijskiActionPerformed

    private void btnDodajUcescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUcescaActionPerformed
        ModelTabeleUcesce mtu = (ModelTabeleUcesce) tabelaUcesce.getModel();
        ArrayList<Ucesce> listaUcesca = mtu.getListaUcesca();
        UcesceForma uf = new UcesceForma(this, true);
        uf.srediTabelu(listaUcesca);
        uf.pack();
        uf.setVisible(true);
    }//GEN-LAST:event_btnDodajUcescaActionPerformed

    private void btnObrisiUcesceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUcesceActionPerformed
        int red = tabelaUcesce.getSelectedRow();
        if(red != -1) {
            ModelTabeleUcesce mtu = (ModelTabeleUcesce) tabelaUcesce.getModel();
            mtu.obrisi(red);
        }else {
            JOptionPane.showMessageDialog(this, "Niste izabrali učešće");
        }
    }//GEN-LAST:event_btnObrisiUcesceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrkeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrkeForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajUcesca;
    private javax.swing.JButton btnIzmeniTrku;
    private javax.swing.JButton btnObrisiUcesce;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvajTrku;
    private javax.swing.JComboBox cmbVrstaTrke;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojUcesnika;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDrzava;
    private javax.swing.JLabel lblDuzina;
    private javax.swing.JLabel lblEvropski;
    private javax.swing.JLabel lblFaza;
    private javax.swing.JLabel lblOlimpijski;
    private javax.swing.JLabel lblPlivaliste;
    private javax.swing.JLabel lblSvetski;
    private javax.swing.JLabel lblVreme;
    private javax.swing.JLabel lblVrsta;
    private javax.swing.JTable tabelaUcesce;
    private javax.swing.JTextField txtBrojUcesnika;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDrzava;
    private javax.swing.JTextField txtDuzina;
    private javax.swing.JTextField txtEvropski;
    private javax.swing.JTextField txtFaza;
    private javax.swing.JTextField txtOlimpijski;
    private javax.swing.JTextField txtPlivaliste;
    private javax.swing.JTextField txtSvetski;
    private javax.swing.JTextField txtVreme;
    // End of variables declaration//GEN-END:variables

    private void srediTabeluUcesca() {
        ModelTabeleUcesce mtu = new ModelTabeleUcesce();
        tabelaUcesce.setModel(mtu);
    }

    void dodajTrku(UcesceForma aThis, Plivac p) {
        try {
            ModelTabeleUcesce mtu = (ModelTabeleUcesce) tabelaUcesce.getModel();
            mtu.dodaj(p);
            JOptionPane.showMessageDialog(this, "Plivač je dodat");
        } catch (IOException ex) {
            Logger.getLogger(TrkeForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void prikaziTrku(int red, JTable tabelaTrke) {
        kontrolerKI.srediFormuPrikaziTrku(red, tabelaTrke, tabelaUcesce, txtDuzina, txtDrzava, txtPlivaliste, txtDatum, txtVreme,txtFaza, txtBrojUcesnika, cmbVrstaTrke, txtEvropski, txtSvetski, txtOlimpijski, btnSacuvajTrku, btnDodajUcesca, btnObrisiUcesce,btnOtkazi, btnIzmeniTrku);
    }

    void unesiRezultate(int red, JTable tabelaTrke) throws Exception {
        kontrolerKI.srediFormuUnesiRezultate(this, red, tabelaTrke, tabelaUcesce, txtDuzina, txtDrzava, txtPlivaliste, txtDatum, txtVreme, txtFaza, txtBrojUcesnika, txtBrojUcesnika, txtEvropski, txtSvetski, txtOlimpijski, cmbVrstaTrke, btnSacuvajTrku, btnDodajUcesca, btnObrisiUcesce, btnIzmeniTrku, btnOtkazi);
    }

    
}
